#!/usr/bin/env python3
"""
generate_progress.py — reads the live checkbox state in tracker/theory/*.md and
tracker/automation/*.md and produces:
  - PROGRESS.md            human-readable progress report (overall + per-phase)
  - badges/theory.json     shields.io "endpoint" badge data
  - badges/automation.json shields.io "endpoint" badge data
  - badges/overall.json    shields.io "endpoint" badge data

This is what .github/workflows/update-progress.yml runs on every push so
PROGRESS.md and the README badges stay in sync with what you've actually
checked off. Safe to run locally any time: `python3 scripts/generate_progress.py`

No third-party dependencies — stdlib only.
"""

import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate_tracker import PHASES  # noqa: E402  (reuse canonical phase titles — single source of truth)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKED_RE = re.compile(r"^- \[[xX]\]", re.MULTILINE)
UNCHECKED_RE = re.compile(r"^- \[ \]", re.MULTILINE)
SLUG_TO_TITLE = {f"{p['slug']}.md": f"Phase {p['id']} — {p['title']}" for p in PHASES}


def count_checkboxes(text):
    checked = len(CHECKED_RE.findall(text))
    unchecked = len(UNCHECKED_RE.findall(text))
    return checked, checked + unchecked


def scan_dir(path):
    """Returns (total_checked, total_tasks, {filename: (checked, total)})"""
    checked_total, total = 0, 0
    per_file = {}
    for fp in sorted(glob.glob(os.path.join(path, "*.md"))):
        with open(fp, encoding="utf-8") as f:
            text = f.read()
        c, t = count_checkboxes(text)
        per_file[os.path.basename(fp)] = (c, t)
        checked_total += c
        total += t
    return checked_total, total, per_file


def pct(c, t):
    return round((c / t) * 100) if t else 0


def bar(p, width=24):
    filled = round(width * p / 100)
    return "█" * filled + "░" * (width - filled)


def color_for(p):
    if p >= 80:
        return "brightgreen"
    if p >= 50:
        return "yellow"
    if p >= 20:
        return "orange"
    return "lightgrey" if p == 0 else "red"


def write_badge(rel_path, label, message, color):
    path = os.path.join(ROOT, rel_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"schemaVersion": 1, "label": label, "message": message, "color": color}, f)


def phase_name(filename):
    return SLUG_TO_TITLE.get(filename, filename.replace(".md", ""))


def main():
    theory_dir = os.path.join(ROOT, "tracker", "theory")
    auto_dir = os.path.join(ROOT, "tracker", "automation")

    theory_c, theory_t, theory_files = scan_dir(theory_dir)
    auto_c, auto_t, auto_files = scan_dir(auto_dir)
    overall_c, overall_t = theory_c + auto_c, theory_t + auto_t

    theory_p, auto_p, overall_p = pct(theory_c, theory_t), pct(auto_c, auto_t), pct(overall_c, overall_t)

    write_badge("badges/theory.json", "theory", f"{theory_p}%", color_for(theory_p))
    write_badge("badges/automation.json", "automation", f"{auto_p}%", color_for(auto_p))
    write_badge("badges/overall.json", "overall progress", f"{overall_p}%", color_for(overall_p))

    lines = [
        "# Progress Report",
        "",
        "_Auto-generated by `scripts/generate_progress.py`. Do not hand-edit — the next "
        "push (or CI run) overwrites this file based on what's actually checked off in "
        "`tracker/theory/*.md` and `tracker/automation/*.md`._",
        "",
        f"**Overall: {overall_p}%**  `{bar(overall_p)}`  ({overall_c}/{overall_t} tasks)",
        "",
        f"- 📘 Theory track: **{theory_p}%**  `{bar(theory_p)}`  ({theory_c}/{theory_t})",
        f"- 🤖 Automation track: **{auto_p}%**  `{bar(auto_p)}`  ({auto_c}/{auto_t})",
        "",
        "## By Phase",
        "",
        "| Phase | Theory | Automation |",
        "|---|---|---|",
    ]

    slugs = sorted(set(list(theory_files.keys()) + list(auto_files.keys())))
    for slug in slugs:
        tc, tt = theory_files.get(slug, (0, 0))
        ac, at = auto_files.get(slug, (0, 0))
        tp, ap = pct(tc, tt), pct(ac, at)
        t_display = f"{tp}% ({tc}/{tt})" if tt else "—"
        a_display = f"{ap}% ({ac}/{at})" if at else "—"
        lines.append(f"| {phase_name(slug)} | {t_display} | {a_display} |")

    lines += [
        "",
        "---",
        "_Regenerate anytime: `python3 scripts/generate_progress.py`. Runs automatically "
        "on every push via `.github/workflows/update-progress.yml`._",
        "",
    ]

    with open(os.path.join(ROOT, "PROGRESS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Overall: {overall_p}% | Theory: {theory_p}% | Automation: {auto_p}%")


if __name__ == "__main__":
    main()
